sudo: required
services:
  - docker
language: generic
before_install: 
  - docker build -t ptargino/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true ptargino/docker-react npm run test